name: Run Python script

on:
  schedule:
    - cron:  '0 10 * * *'  # 这行表示每天的 UTC 时间10点执行
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest  # 运行环境

    steps:
    - uses: actions/checkout@v2  # 拉取代码

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # 设置 Python 版本
        cache: 'pip'
    
    - name: selenium
      run: |
        curl https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o chrome.deb
        dpkg -i chrome.deb
        apt -f install

    - name: Check-in JD
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 如果有依赖，可以在这里安装

    - name: Run script
      run: python main.py  # 执行你的 Python 文件
